// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeMusicPlayer.MusicManagement.Infrastructure.EF;

namespace YoutubeMusicPlayer.MusicManagement.Infrastructure.EF.Migrations
{
    [DbContext(typeof(MusicManagementDbContext))]
    partial class MusicManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("YoutubeMusicPlayer.MusicManagement.Domain.Entities.MainPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("music_management$main_playlist");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c90db7f6-ad0f-45da-879f-6ba326401f17"),
                            Name = "Main Playlist"
                        });
                });

            modelBuilder.Entity("YoutubeMusicPlayer.MusicManagement.Domain.Entities.MainPlaylist", b =>
                {
                    b.OwnsMany("YoutubeMusicPlayer.MusicManagement.Domain.Entities.Song", "Songs", b1 =>
                        {
                            b1.Property<Guid>("MainPlaylistId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Artist")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SongPath")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ThumbnailUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Title")
                                .HasColumnType("TEXT");

                            b1.Property<string>("YtId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MainPlaylistId", "Id");

                            b1.ToTable("music_management$main_playlist_song");

                            b1.WithOwner()
                                .HasForeignKey("MainPlaylistId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
