// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeMusicPlayer.IntegrationTests.Infrastructure.EFCore;

namespace YoutubeMusicPlayer.IntegrationTests.Infrastructure.EFCore.Migrations.Module2
{
    [DbContext(typeof(Module2DbContext))]
    [Migration("20200217201817_Setup Migration")]
    partial class SetupMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("YoutubeMusicPlayer.IntegrationTests.Infrastructure.EFCore.Entity2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("module2_entities");
                });
#pragma warning restore 612, 618
        }
    }
}
